version: '3.6'
services:
  home-assistant:
    image: homeassistant/home-assistant:stable
    volumes:
      - ./config:/config
    environment:
      - TZ=Europe/Paris
    restart: always
    ports: 
      - 8123:8123

  mqtt:
    image: eclipse-mosquitto:1.6.9
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mqtt/config:/mosquitto/config
    environment:
      - TZ=Europe/Paris
