
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  name: Maison
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: Europe/Paris

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


frontend:
  themes: !include_dir_merge_named themes


mqtt:
  broker: mqtt
  port: 1883
  client_id: home-assistant
  username: !secret MQTT_username
  password: !secret MQTT_password


hue:
  bridges:
    - host: 192.168.10.76
      allow_unreachable: true
      allow_hue_groups: false